name: "Lint and Format Check"
description: "Run ESLint and Prettier checks"

runs:
  using: "composite"
  steps:
    - name: Run linting
      run: npm run lint:eslint
      shell: bash

    - name: Run format check
      run: npm run lint:prettier
      shell: bash
